version: '3.8'

services:
  web:
    build: .
    container_name: drf-app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - opensearch
    environment:
      - DEBUG=1
      - DB_NAME=drfapp
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=3306
      - OPENSEARCH_HOST=http://opensearch:9200
      - DJANGO_SETTINGS_MODULE=core.settings  # ✅ add this line
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000

  db:
    image: mysql:8
    container_name: drf-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drfapp
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  opensearch:
    image: opensearchproject/opensearch:2.11.1
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin  # optional, required if auth is ON
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearchdata:/usr/share/opensearch/data
  
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.1
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    depends_on:
      - opensearch
  
  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  dbdata:
  opensearchdata:
